services:

  mariadb:
    image: mariadb
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

  wordpress:
    image: wordpress
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    image: nginx
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: on-failure

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge